### ISSUE TITLE
Fio API not working since November 2015

### ISSUE THREAD

**Issue by mArtinko5MB** [robinbortlik/fio_api#5]
Hello friend,

i am writing to let you know that fio api is not working anymore since november 2015. The thing is that API can not resolve response from server (from url).

When i type in browser link with params i get response in xml. But this 

		FioAPI.token = data["token"].strip
		list = FioAPI::List.new
		list.by_date_range(datum_od, datum_do)

		list.response

always return '[ ]' (empty array). I am sure it's minor issue you can fix in a minute ... Please would you be so nice and look at it? I am using your gem daily 

Thanks for response

**Comment by robinbortlik** [comment]
Hi @mArtinko5MB , if I will have a time through the weekend, I will take a look on it. But your PR is always welcome ;)

**Comment by robinbortlik** [comment]
@mArtinko5MB , can you please set your gem source to github and test it? Thank you.

**Comment by robinbortlik** [comment]
Ok, new version released as 0.0.5 . Thanks a lot for your help guys.

**Comment by mArtinko5MB** [comment]
Thanks a lot
